# docker build -t go_hexa_grpc . -f Dockerfile-grpc
# docker run -dit --name grpc -p 50051:50052 go_hexa_grpc

FROM golang:1.17 As builder
WORKDIR /app

COPY . .
WORKDIR /app/cmd/balance/grpc
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w' -o go_hexa_grpc

FROM scratch
WORKDIR /app
COPY --from=builder /app/cmd/balance/grpc/go_hexa_grpc .
CMD ["/app/go_hexa_grpc"]