# docker build -t go_hexa_http . -f Dockerfile-http
# docker run -dit --name go_hexa_http -p 8900:8900 go_hexa_http 

FROM golang:1.17 As builder
WORKDIR /app

COPY . .
WORKDIR /app/cmd/balance/http
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w' -o go_hexa_http

FROM scratch
WORKDIR /app
COPY --from=builder /app/cmd/balance/http/go_hexa_http .
CMD ["/app/go_hexa_http"]