apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hexa-grpc
  namespace: test-g
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-hexa-grpc
  template:
    metadata:
      labels:
        app: go-hexa-grpc
        version: "go-hexa-grpc"
    spec:
      containers:
      - name: go-hexa-grpc
        imagePullPolicy: Never
        image: go_hexa_grpc
        resources:
           requests:
             cpu: 250m
             memory: 100Mi
           limits:
             cpu: 500m
             memory: 200Mi
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: NAME_POD
          value: "pod-go-hexa-grpc"
      terminationGracePeriodSeconds: 60
