apiVersion: v1
kind: Service
metadata:
  name: svc-go-hexa-http
  namespace: test-g
spec:
  ports:
  - name: svc-go-hexa-http
    port: 8001
    targetPort: 8001
  selector:
    app: go-hexa-http
  type: LoadBalancer